-- Insert dummy data for Programs
INSERT INTO master_programs (user_id, name, code, description, type, duration, campus, delivery_method, status, color, category, tags, entry_requirements, document_requirements, fee_structure, is_active) VALUES
(auth.uid(), 'Bachelor of Science in Computer Science', 'CS101', 'Comprehensive computer science program covering software development, algorithms, and system design', 'undergraduate', '4 years', 'Main Campus', 'on_campus', 'active', '#3B82F6', 'STEM', '["High School Diploma", "Mathematics Prerequisites"]'::text[], '{"gpa": 3.0, "english_proficiency": "IELTS 6.5"}'::jsonb, '["Academic Transcripts", "Personal Statement", "English Proficiency"]'::jsonb, '{"tuition": 45000, "currency": "USD", "payment_plan": "semester"}'::jsonb, true),
(auth.uid(), 'Master of Business Administration', 'MBA001', 'Advanced business administration program for leadership and management', 'postgraduate', '2 years', 'Main Campus', 'hybrid', 'active', '#EF4444', 'Business', '["Bachelor Degree", "Work Experience"]'::text[], '{"gpa": 3.2, "work_experience": "2+ years", "gmat": 550}'::jsonb, '["Academic Transcripts", "Personal Statement", "Work Experience Letter", "GMAT Scores"]'::jsonb, '{"tuition": 65000, "currency": "USD", "payment_plan": "semester"}'::jsonb, true),
(auth.uid(), 'Certificate in Digital Marketing', 'DM101', 'Professional certificate in modern digital marketing strategies', 'certificate', '6 months', 'Online Campus', 'online', 'active', '#10B981', 'Marketing', '["Basic Computer Skills"]'::text[], '{"portfolio": "recommended"}'::jsonb, '["Portfolio", "Identity Document"]'::jsonb, '{"tuition": 8500, "currency": "USD", "payment_plan": "monthly"}'::jsonb, true),
(auth.uid(), 'Bachelor of Arts in Psychology', 'PSY101', 'Study of human behavior and mental processes', 'undergraduate', '3 years', 'Main Campus', 'on_campus', 'active', '#8B5CF6', 'Social Sciences', '["High School Diploma"]'::text[], '{"gpa": 2.8}'::jsonb, '["Academic Transcripts", "Personal Statement"]'::jsonb, '{"tuition": 38000, "currency": "USD", "payment_plan": "semester"}'::jsonb, true),
(auth.uid(), 'Diploma in Nursing', 'NUR201', 'Professional nursing diploma with clinical practice', 'diploma', '2 years', 'Main Campus', 'on_campus', 'active', '#F59E0B', 'Health Sciences', '["High School Diploma", "Health Clearance"]'::text[], '{"gpa": 3.0, "health_check": true}'::jsonb, '["Academic Transcripts", "Medical Certificate", "Background Check"]'::jsonb, '{"tuition": 32000, "currency": "USD", "payment_plan": "semester"}'::jsonb, true);

-- Insert dummy data for Campuses
INSERT INTO master_campuses (user_id, name, code, address, city, state, country, postal_code, phone, email, website, timezone, capacity, facilities, is_active) VALUES
(auth.uid(), 'Main Campus', 'MC01', '123 University Drive', 'Sydney', 'NSW', 'Australia', '2000', '+61-2-9123-4567', 'main@university.edu.au', 'https://main.university.edu.au', 'Australia/Sydney', 15000, '["Library", "Sports Complex", "Student Housing", "Medical Center", "Cafeteria", "Computer Labs"]'::text[], true),
(auth.uid(), 'North Campus', 'NC01', '456 Education Street', 'Melbourne', 'VIC', 'Australia', '3000', '+61-3-9876-5432', 'north@university.edu.au', 'https://north.university.edu.au', 'Australia/Melbourne', 8000, '["Library", "Computer Labs", "Cafeteria", "Parking", "Student Services"]'::text[], true),
(auth.uid(), 'Online Campus', 'OC01', 'Virtual Learning Environment', 'Virtual', NULL, 'Global', NULL, '+1-800-555-0199', 'online@university.edu', 'https://online.university.edu', 'UTC', 50000, '["Online Platform", "Virtual Labs", "Digital Library", "Video Conferencing", "24/7 Support"]'::text[], true),
(auth.uid(), 'International Campus', 'IC01', '789 Global Avenue', 'Singapore', NULL, 'Singapore', '138623', '+65-6123-4567', 'singapore@university.edu.sg', 'https://singapore.university.edu', 'Asia/Singapore', 5000, '["Library", "International Student Services", "Accommodation", "Cultural Center", "Language Lab"]'::text[], true);

-- Insert dummy data for Marketing Sources
INSERT INTO master_marketing_sources (user_id, name, category, description, cost_per_lead, conversion_rate, tracking_parameters, is_active) VALUES
(auth.uid(), 'Google Ads', 'paid_advertising', 'Search engine marketing campaigns targeting education keywords', 25.50, 0.12, '{"utm_source": "google", "utm_medium": "cpc", "utm_campaign": "education"}'::jsonb, true),
(auth.uid(), 'Facebook Ads', 'social_media', 'Social media advertising campaigns on Facebook and Instagram', 18.75, 0.08, '{"utm_source": "facebook", "utm_medium": "paid_social", "utm_campaign": "awareness"}'::jsonb, true),
(auth.uid(), 'LinkedIn', 'social_media', 'Professional network advertising targeting working professionals', 35.00, 0.15, '{"utm_source": "linkedin", "utm_medium": "paid_social", "utm_campaign": "professionals"}'::jsonb, true),
(auth.uid(), 'Email Campaigns', 'email_marketing', 'Direct email marketing to prospect database', 5.25, 0.06, '{"utm_source": "email", "utm_medium": "email", "utm_campaign": "nurture"}'::jsonb, true),
(auth.uid(), 'Referrals', 'word_of_mouth', 'Student and alumni referral program', 0.00, 0.25, '{"utm_source": "referral", "utm_medium": "word_of_mouth", "utm_campaign": "referral_program"}'::jsonb, true),
(auth.uid(), 'Organic Search', 'seo', 'Search engine optimization results from Google', 0.00, 0.18, '{"utm_source": "google", "utm_medium": "organic", "utm_campaign": "seo"}'::jsonb, true),
(auth.uid(), 'Education Fairs', 'events', 'Participation in education exhibitions and fairs', 150.00, 0.22, '{"utm_source": "events", "utm_medium": "offline", "utm_campaign": "education_fairs"}'::jsonb, true),
(auth.uid(), 'Print Media', 'traditional', 'Newspaper and magazine advertisements', 45.00, 0.04, '{"utm_source": "print", "utm_medium": "traditional", "utm_campaign": "brand_awareness"}'::jsonb, false);

-- Insert dummy data for Communication Templates
INSERT INTO master_communication_templates (user_id, name, type, category, subject, content, variables, conditional_logic, is_system_template, is_active, usage_count, tags) VALUES
(auth.uid(), 'Welcome Email', 'email', 'onboarding', 'Welcome to {{university_name}}!', 'Dear {{first_name}},\n\nWelcome to our university! We are excited to have you join our community. Your journey in {{program_name}} starts here.\n\nBest regards,\nAdmissions Team', '["first_name", "university_name", "program_name"]'::jsonb, '{"conditions": [{"field": "status", "operator": "equals", "value": "admitted"}]}'::jsonb, false, true, 0, '["welcome", "onboarding", "email"]'::text[]),
(auth.uid(), 'Application Received', 'email', 'application', 'Application Received - {{application_id}}', 'Thank you {{first_name}} for submitting your application for {{program_name}}. Your application ID is {{application_id}}.\n\nWe will review your application and contact you within 5-7 business days.\n\nAdmissions Team', '["first_name", "application_id", "program_name"]'::jsonb, NULL, false, true, 0, '["application", "confirmation", "email"]'::text[]),
(auth.uid(), 'Interview Invitation', 'email', 'interview', 'Interview Invitation - {{program_name}}', 'Dear {{first_name}},\n\nWe would like to invite you for an interview for {{program_name}} on {{interview_date}} at {{interview_time}}.\n\nPlease confirm your attendance.\n\nBest regards,\nAdmissions Team', '["first_name", "program_name", "interview_date", "interview_time"]'::jsonb, '{"conditions": [{"field": "application_status", "operator": "equals", "value": "under_review"}]}'::jsonb, false, true, 0, '["interview", "invitation", "email"]'::text[]),
(auth.uid(), 'Admission Decision', 'email', 'decision', 'Admission Decision - {{program_name}}', 'Dear {{first_name}},\n\nWe are pleased to inform you about your admission status for {{program_name}}. Decision: {{decision}}.\n\nDeadline to accept: {{deadline}}\n\nCongratulations!\nAdmissions Team', '["first_name", "program_name", "decision", "deadline"]'::jsonb, '{"conditions": [{"field": "decision", "operator": "in", "value": ["accepted", "conditional"]}]}'::jsonb, false, true, 0, '["decision", "admission", "email"]'::text[]),
(auth.uid(), 'Payment Reminder', 'sms', 'payment', 'Payment Due Reminder', 'Hi {{first_name}}, your payment of ${{amount}} is due on {{due_date}}. Please complete payment to secure your enrollment. Reply STOP to opt out.', '["first_name", "amount", "due_date"]'::jsonb, '{"conditions": [{"field": "payment_status", "operator": "equals", "value": "pending"}]}'::jsonb, false, true, 0, '["payment", "reminder", "sms"]'::text[]),
(auth.uid(), 'Document Submission Reminder', 'email', 'documents', 'Missing Documents - Action Required', 'Dear {{first_name}},\n\nWe are missing the following documents for your application: {{missing_documents}}.\n\nPlease submit by {{deadline}} to avoid delays.\n\nAdmissions Team', '["first_name", "missing_documents", "deadline"]'::jsonb, '{"conditions": [{"field": "documents_complete", "operator": "equals", "value": false}]}'::jsonb, false, true, 0, '["documents", "reminder", "email"]'::text[]),
(auth.uid(), 'Enrollment Confirmation', 'email', 'enrollment', 'Enrollment Confirmed - {{program_name}}', 'Congratulations {{first_name}}!\n\nYour enrollment in {{program_name}} has been confirmed. Classes start on {{start_date}} at {{campus}}.\n\nWelcome to the university family!\nStudent Services', '["first_name", "program_name", "start_date", "campus"]'::jsonb, '{"conditions": [{"field": "enrollment_status", "operator": "equals", "value": "confirmed"}]}'::jsonb, false, true, 0, '["enrollment", "confirmation", "email"]'::text[]),
(auth.uid(), 'Follow-up Call Script', 'call_script', 'follow_up', 'Follow-up Call', 'Hello {{first_name}}, this is {{agent_name}} from {{university_name}}. I am calling to follow up on your application for {{program_name}}. Status: {{application_status}}. Do you have any questions I can help with today?', '["first_name", "agent_name", "university_name", "program_name", "application_status"]'::jsonb, NULL, false, true, 0, '["call", "follow_up", "script"]'::text[]);

-- Insert dummy data for Call Types
INSERT INTO master_call_types (user_id, name, description, duration_estimate, follow_up_required, template_notes, is_active) VALUES
(auth.uid(), 'Initial Consultation', 'First contact call with prospective student to understand their needs and explain programs', 30, true, 'Focus on understanding student goals, explain program options, gather contact information for follow-up', true),
(auth.uid(), 'Follow-up Call', 'Follow-up call after initial consultation to answer additional questions', 15, true, 'Address any questions from previous call, provide additional program details, schedule next steps', true),
(auth.uid(), 'Information Session', 'Detailed program information session including curriculum and career prospects', 45, true, 'Comprehensive program overview, career outcomes, admission requirements, financial aid options', true),
(auth.uid(), 'Application Review', 'Call to review application status and required documents', 20, true, 'Review application completeness, discuss missing documents, explain next steps in process', true),
(auth.uid(), 'Enrollment Confirmation', 'Final enrollment confirmation and next steps discussion', 25, false, 'Confirm enrollment details, discuss orientation, provide student portal access, answer final questions', true),
(auth.uid(), 'Technical Support', 'Support call for application portal or technical issues', 15, false, 'Troubleshoot technical issues, provide step-by-step guidance, escalate complex issues if needed', true);

-- Insert dummy data for Notification Filters
INSERT INTO master_notification_filters (user_id, name, type, event_types, conditions, recipients, frequency, is_active) VALUES
(auth.uid(), 'New Lead Alert', 'lead_creation', '["lead_created", "form_submitted"]'::text[], '{"sources": ["Google Ads", "LinkedIn"], "priority": "high", "lead_score": {"min": 70}}'::jsonb, '{"roles": ["admissions"], "emails": ["admissions@university.edu"]}'::jsonb, 'immediate', true),
(auth.uid(), 'Application Deadline', 'deadline_reminder', '["deadline_approaching", "deadline_passed"]'::text[], '{"days_before": 7, "stage": "application", "programs": ["Master of Business Administration"]}'::jsonb, '{"roles": ["advisors"], "students": true}'::jsonb, 'daily', true),
(auth.uid(), 'Payment Overdue', 'payment_status', '["payment_overdue", "payment_failed"]'::text[], '{"status": "overdue", "days_overdue": 3, "amount_threshold": 1000}'::jsonb, '{"roles": ["finance", "student_services"], "escalation": true}'::jsonb, 'daily', true),
(auth.uid(), 'Document Missing', 'document_status', '["document_missing", "document_rejected"]'::text[], '{"status": "missing", "mandatory": true, "days_since_request": 5}'::jsonb, '{"roles": ["document_reviewers"], "students": true}'::jsonb, 'weekly', true),
(auth.uid(), 'High Value Lead', 'lead_scoring', '["lead_scored", "lead_updated"]'::text[], '{"score_threshold": 80, "source_quality": "premium", "program_interest": ["Master of Business Administration", "Bachelor of Science in Computer Science"]}'::jsonb, '{"roles": ["senior_advisors"], "priority_queue": true}'::jsonb, 'immediate', true),
(auth.uid(), 'Interview Scheduled', 'interview_booking', '["interview_scheduled", "interview_rescheduled"]'::text[], '{"event_type": "interview", "lead_time_hours": 24}'::jsonb, '{"roles": ["admissions", "interviewers"], "students": true, "calendar_integration": true}'::jsonb, 'immediate', true);

-- Insert dummy data for Requirements
INSERT INTO master_requirements (user_id, name, type, category, description, minimum_value, maximum_value, units, is_mandatory, applicable_programs, verification_method, documentation_required, is_active) VALUES
(auth.uid(), 'IELTS Score', 'language_proficiency', 'academic', 'International English Language Testing System score requirement', '6.5', '9.0', 'score', true, '["Bachelor of Science in Computer Science", "Master of Business Administration"]'::text[], 'official_transcript', '["IELTS Certificate", "Test Report Form"]'::text[], true),
(auth.uid(), 'GPA Requirement', 'academic_performance', 'academic', 'Minimum Grade Point Average for admission', '3.0', '4.0', 'gpa', true, '["Master of Business Administration"]'::text[], 'transcript_verification', '["Official Transcripts", "Grade Reports"]'::text[], true),
(auth.uid(), 'Work Experience', 'professional_experience', 'professional', 'Minimum work experience requirement', '2', '10', 'years', false, '["Master of Business Administration"]'::text[], 'employer_verification', '["Work Experience Letter", "Employment Certificate", "Resume"]'::text[], true),
(auth.uid(), 'Age Requirement', 'demographic', 'eligibility', 'Age restrictions for certain programs', '18', '65', 'years', true, '["All Programs"]'::text[], 'identity_verification', '["Birth Certificate", "Passport", "National ID"]'::text[], true),
(auth.uid(), 'Financial Capacity', 'financial', 'financial', 'Proof of financial ability to complete the program', '50000', NULL, 'USD', true, '["All Programs"]'::text[], 'bank_verification', '["Bank Statement", "Scholarship Letter", "Sponsor Letter"]'::text[], true),
(auth.uid(), 'Health Clearance', 'medical', 'health', 'Medical clearance for health-related programs', NULL, NULL, NULL, true, '["Diploma in Nursing"]'::text[], 'medical_examination', '["Medical Certificate", "Vaccination Records", "Health Clearance"]'::text[], true),
(auth.uid(), 'Background Check', 'security', 'eligibility', 'Criminal background check requirement', NULL, NULL, NULL, true, '["Diploma in Nursing"]'::text[], 'police_verification', '["Police Clearance Certificate", "Background Check Report"]'::text[], true),
(auth.uid(), 'Portfolio Submission', 'creative', 'academic', 'Portfolio requirement for creative programs', '5', '20', 'pieces', false, '["Certificate in Digital Marketing"]'::text[], 'portfolio_review', '["Digital Portfolio", "Project Samples", "Creative Work"]'::text[], true);

-- Insert dummy data for Teams (External Recruiters)
INSERT INTO master_teams (user_id, name, type, description, specializations, region, max_daily_assignments, working_hours, contact_email, contact_phone, performance_metrics, is_active) VALUES
(auth.uid(), 'Internal Admissions Team', 'internal', 'In-house admissions team handling all program inquiries and applications', '["All Programs", "General Inquiries", "Application Processing"]'::text[], 'Global', 50, '{"timezone": "UTC", "start": "09:00", "end": "17:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}'::jsonb, 'admissions@university.edu', '+1-555-0100', '{"conversion_rate": 0.18, "avg_response_time": 2.5, "satisfaction_score": 4.7}'::jsonb, true),
(auth.uid(), 'Asia Pacific Recruiters', 'external', 'External recruitment partners covering Asia Pacific region', '["Business Programs", "Technology Programs", "Graduate Programs"]'::text[], 'Asia Pacific', 30, '{"timezone": "Asia/Singapore", "start": "09:00", "end": "18:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]}'::jsonb, 'apac@recruiters.com', '+65-6789-0123', '{"conversion_rate": 0.22, "avg_response_time": 4.2, "satisfaction_score": 4.5}'::jsonb, true),
(auth.uid(), 'European Education Partners', 'external', 'Trusted education consultants across European markets', '["All Programs", "International Students", "Exchange Programs"]'::text[], 'Europe', 25, '{"timezone": "Europe/London", "start": "08:00", "end": "17:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}'::jsonb, 'europe@edupartners.com', '+44-20-7123-4567', '{"conversion_rate": 0.16, "avg_response_time": 3.8, "satisfaction_score": 4.3}'::jsonb, true),
(auth.uid(), 'North America Agents', 'external', 'Specialized agents for North American market', '["Graduate Programs", "Professional Certificates", "Executive Education"]'::text[], 'North America', 35, '{"timezone": "America/New_York", "start": "09:00", "end": "17:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}'::jsonb, 'na@educationagents.com', '+1-555-0200', '{"conversion_rate": 0.20, "avg_response_time": 3.2, "satisfaction_score": 4.6}'::jsonb, true),
(auth.uid(), 'Middle East Representatives', 'external', 'Regional representatives for Middle East and North Africa', '["Business Programs", "Health Sciences", "Professional Development"]'::text[], 'Middle East', 20, '{"timezone": "Asia/Dubai", "start": "08:00", "end": "16:00", "days": ["sunday", "monday", "tuesday", "wednesday", "thursday"]}'::jsonb, 'me@globalreps.com', '+971-4-123-4567', '{"conversion_rate": 0.19, "avg_response_time": 4.5, "satisfaction_score": 4.4}'::jsonb, true);